name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      tags:
        description: 'Tags to run specific tests'
        required: false
      workers:
        description: 'Number of parallel test workers'
        required: false
        default: 'auto'
      test_data:
        description: 'Path to test data file or directory'
        required: false
      browser:
        description: 'Browser to use for testing'
        required: false
        default: 'chrome'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Run tests
      run:  |
        # Default values for inputs
        TAGS=${{ github.event.inputs.tags || 'smoke' }}
        WORKERS=${{ github.event.inputs.workers || 'auto' }}
        TEST_DATA=${{ github.event.inputs.test_data || 'tests/test_data' }}
        BROWSER=${{ github.event.inputs.browser || 'chrome' }}
        
        # Execute tests with variables
        bash -c "pytest --browser=${BROWSER} --tags=${TAGS} -n=${WORKERS} --test_data=${TEST_DATA} --headless --html=reports/report.html"
    - name: Upload test report
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: report/report.html

