name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      tags:
        description: 'Tags to run specific tests'
        required: false
      workers:
        description: 'Number of parallel test workers'
        required: false
        default: 'auto'
      test_data:
        description: 'Path to test data file or directory'
        required: false
      browser:
        description: 'Browser to use for testing'
        required: false
        default: 'chrome'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Run tests
      run: |
        bash -c "cd tests && pytest --browser=chrome --tags=all --test_data_file=test_data/test_data.json
        ../tests/test_login.py"

    - name: Upload test report
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: report/report.html

